[versions]
clikt = "3.5.0"                             # https://ajalt.github.io/clikt/changelog/
compose-ui = "1.3.2"
i18n4k-core = "0.5.0"                       # https://github.com/comahe-de/i18n4k/releases
junit = "4.13.2"
kamel = "0.5-darwinandjs0"                  # https://github.com/alialbaali/Kamel/pull/23
kermit = "1.2.2"                            # https://github.com/touchlab/Kermit/releases
koin = "3.4.0"                              # https://github.com/InsertKoinIO/koin/blob/main/CHANGELOG.md
kotlinx-collections-immutable = "0.3.5"     # https://github.com/Kotlin/kotlinx.collections.immutable/blob/master/CHANGELOG.md
kotlinx-datetime = "0.4.0"                  # https://github.com/Kotlin/kotlinx-datetime/blob/master/CHANGELOG.md
kotlinx-serialization-json = "1.5.0"        # https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md
ktor = "2.2.4"                              # https://github.com/ktorio/ktor/blob/main/CHANGELOG.md
mp_stools = "1.2.2"                         # https://github.com/sergeych/mp_stools/releases
multiplatform-settings = "1.0.0"            # https://github.com/russhwolf/multiplatform-settings/blob/master/CHANGELOG.md
okio = "3.3.0"                              # https://square.github.io/okio/changelog/
slf4j-slf4j-nop = "1.7.21"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
i18n4k-core = { module = "de.comahe.i18n4k:i18n4k-core", version.ref = "i18n4k-core" }
i18n4k-core-js = { module = "de.comahe.i18n4k:i18n4k-core-js", version.ref = "i18n4k-core" }
junit = { module = "junit:junit", version.ref = "junit" }
kamel-image = { module = "io.github.luca992.com.alialbaali.kamel:kamel-image", version.ref = "kamel" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
mp_stools = { module = "net.sergeych:mp_stools", version.ref = "mp_stools" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-nodefilesystem = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }
slf4j-slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j-slf4j-nop" }

[plugins]
